development:
  bucket: your bucket
  access_key_id: your access key id
  secret_access_key: your secret access key

test:
  bucket: your bucket
  access_key_id: your access key id
  secret_access_key: your secret key

production:
  bucket: bucket name here
  access_key_id: access key id here
  secret_access_key: super secret key
